### ISSUE TITLE
Build Lineage-13

### ISSUE THREAD

**Issue by IKGapirov** [diepquynh/android_device_samsung_coreprimeve3g#2]
Good Day!
Great rom, thanks for u for the hard work. 
I'm trying to build Lineage-13. When trying to compile i receive this error:
https://gist.github.com/IKGapirov/c5f253ef8a34f418935b786ebb34d357
can u advise something about it(
Thank you in advance!

**Comment by ngoquang2708** [comment]
I think you should remove all hardware module packages for you board first. Then reenable each of them after the build successed.
